[package]
name = "common-cache"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = "1.9.2"
rand = "0.8.5"
replace_with = "0.1.7"

[dev-dependencies]
assert_matches = "1.5.0"
