[workspace]
members = ["zulib", "zcli", "clap-repl", "common-cache"]
resolver = "2"

[workspace.dependencies]
clap = "4.0.32"

[patch.crates-io]
serde = { git = "https://github.com/tage64/serde" }
cc-traits = { git = "https://github.com/tage64/cc-traits" }
