comment_width = 100
format_code_in_doc_comments = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
version = "Two"
wrap_comments = true
